repos:
  - repo: local
    hooks:
    - id: isort
      args: [--filter-files]
      name: isort
      stages: [commit]
      language: system
      entry: poetry run isort
      types: [python]

    - id: flake8
      exclude: |
        (?x)(
            ^migrations/|
        )
      name: flake8
      stages: [commit]
      language: system
      entry: poetry run flake8 --max-line-length 88
      types: [python]

    - id: mypy
      args: [--show-error-codes]
      name: mypy
      stages: [commit]
      language: system
      entry: poetry run mypy
      types: [python]
      require_serial: true
