version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/openweather_task
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env

