"""Add item sendings table

Revision ID: b36f4b466a79
Revises: be1abbe79118
Create Date: 2020-10-27 13:50:22.558952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36f4b466a79'
down_revision = 'be1abbe79118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('confirmation_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sendings_from_user_id'), 'sendings', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_sendings_id'), 'sendings', ['id'], unique=False)
    op.create_index(op.f('ix_sendings_item_id'), 'sendings', ['item_id'], unique=False)
    op.create_index(op.f('ix_sendings_to_user_id'), 'sendings', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sendings_to_user_id'), table_name='sendings')
    op.drop_index(op.f('ix_sendings_item_id'), table_name='sendings')
    op.drop_index(op.f('ix_sendings_id'), table_name='sendings')
    op.drop_index(op.f('ix_sendings_from_user_id'), table_name='sendings')
    op.drop_table('sendings')
    # ### end Alembic commands ###
